#!/bin/bash

booted=""
until [[ "$booted" =~ "stopped" ]]; do
    # -e directs command to the only running emulator
    booted=`adb -e shell getprop init.svc.bootanim`
    echo "$booted"
    if [[ "$booted" =~ "not found" ]]; then
        echo "Could not boot emulator"
        exit 1
    fi
    sleep 1
done
echo "Emulator booted"
